### ISSUE TITLE
部分机型不兼容的问题

### ISSUE THREAD

**Issue by 1izheng** [kareluo/AndroidPicturePreview#7]
try {
      mImageRegion = decoder.newRegionDecoder();
} catch (IOException e) {
      throw new RuntimeException("无法访问图片");
}

这里直接崩了 如何解决呢?

**Comment by minetsh** [comment]
新版本会将异常抛出去，你现在可以在catch中打一个断点查看下具体异常，大部分应该是文件无法读取问题，小米3手机等测试过时没有问题的
